##以下配置全部是从nacos配置中心读取的
#
#
#spring:
#  #配置数据源
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 362623
#    url: jdbc:mysql://192.168.200.131:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
#  cloud:
#    sentinel:
#      transport:
#        dashboard: localhost:8080  #sentinel控制台地址
#        port: 8719  #指定应用与Sentinel控制台交互的端口，应用本地会起一个该端口占用的HttpServer,#默认8719，假如被占用了会自动从8719开始依次+1扫描。直至找到未被占用的端口
#
#  session:
#    store-type: redis #指定使用redis来保存session数据
#    redis:
#      namespace: spring:session #存储的命名空间
#
#  redis:  #配置redis
#    host: 192.168.200.132
#    port: 6379
#
#  cache:
#    type: redis #配置使用redis作为缓存
#    redis:
#      time-to-live: 3600000 #设置1个小时的存活时间
#      key-prefix: SpringCache_  #每个缓存空间的前缀
#      use-key-prefix: true  #是否使用缓存前缀
#      cache-null-values: true   #是否使用缓存空值，防止缓存穿透
#
#  #配置RabbitMQ
#  rabbitmq:
#    host: 192.168.200.132
#    port: 5672
#    virtual-host: /gulimall #虚拟主机名称
#    username: admin
#    password: 362623
#    publisher-confirm-type: simple  #开启消息发送到服务端确认回调
#    publisher-returns: true #开启消息抵达队列返回回调
#    template:
#      mandatory: true #只要抵达队列，以异步发送优先回调我们这个returnConfirm
#    listener:
#      simple:
#        acknowledge-mode: manual  #开始手动确认消息
#
#  #指定返回日期的格式
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#  #关闭页面缓存
#  thymeleaf:
#    cache: false
#
##配置mybatis-plus
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml  #mapper文件位置
#  global-config:
#    db-config:
#      id-type: auto #表示使用数据库主键自增
#
##打印sql日志
#logging:
#  level:
#    gulimall:
#      order:
#        dao: debug
#

##配置我们自定义的线程池参数，想在配置文件中获得提示需要引入spring-boot-configuration-processor依赖
#gulimall:
#  thread:
#    core-pool-size: 20
#    maximum-pool-size: 200
#    keep-alive-time: 10
#
#seata:
#  enabled: true
#  application-id: gulimall-order #服务唯一id,使用当前服务名称即可
#  tx-service-group: gulimall-order-group #service.vgroupMapping后面跟着的名字(每个服务一个)
#  enable-auto-data-source-proxy: true #自动数据源代理
#  config: #配置中心的相关配置
#    type: nacos
#    nacos:
#      namespace: 8168949a-6a7a-48ac-b12d-8866fa941b01
#      serverAddr: localhost:8848
#      group: SEATA_GROUP
#      userName: "nacos"
#      password: "nacos"
#  registry: #注册中心相关配置
#    type: nacos
#    nacos:
#      application: seata-server
#      server-addr: localhost:8848
#      namespace:
#      userName: "nacos"
#      password: "nacos"
#
##配置自定义的支付宝配置参数
#alipay:
#  alipay-public-key: 支付宝公钥
#  app-id: 2021000118636676
#  merchant-private-key: 商户私钥
#  notify-url: http://q740km4v.xiaomy.net/paymentNotifications #该地址必须外网可访问，因为是支付宝给我们发信息(这里使用的是内网穿透)
#  return-url: http://order.gulimall.com/list.html
#  sign-type: RSA2
#  charset: utf-8
#  gateway-url: https://openapi.alipaydev.com/gateway.do
#  timeout-express: 30m
#
##暴露所有端点,actuator健康监控
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#feign:
#  sentinel:
#    enabled: true #开启feign对sentinel的支持